services:
  comfyui:
    image: ghcr.io/dreamhoney-j/comfyui_cpu_docker:main
    container_name: comfyui-cpu
    ports:
      - "8188:8188"
    volumes:
      - ./ComfyUI:/app/ComfyUI
    restart: unless-stopped
