services:
  comfyui:
    image: ghcr.io/dreamhoney-j/comfyui_cpu_docker:main
    container_name: comfyui-cpu
    ports:
      - "8188:8188"
    volumes:
      - ./data/models:/app/ComfyUI/models
      - ./data/output:/app/ComfyUI/output
      - ./data/input:/app/ComfyUI/input
    restart: unless-stopped